<?php /** @var \ShoppingFeed\Manager\Block\Adminhtml\Sales\Order\View\Item\MarketplaceFields $block */ ?>
<?php $_fields = $block->getMarketplaceFields(); ?>
<?php if (!empty($_fields)): ?>
<tr>
    <td colspan="10" class="last">
        <?php foreach ($block->getMarketplaceFields() as $code => $value): ?>
            <p>
                <span><?= $block->escapeHtml($code) ?>:</span>
                <?php if ($block->getFieldFormat($code) === \ShoppingFeed\Manager\Block\Adminhtml\Sales\Order\View\Item\MarketplaceFields::FORMAT_LINK): ?>
                    <a href="<?= $block->escapeUrl($value) ?>"><?= $block->escapeHtml($value) ?></a><br />
                <?php else: ?>
                    <?= $block->escapeHtml($value) ?><br />
                <?php endif ?>
            </p>
        <?php endforeach; ?>
    </td>
</tr>
<?php endif ?>
